version: "3.8"
services:
  test-runner:
    container_name: test-runner
    image: test-runner:latest
    command: yarn test
    networks:
      - default
      - proxy

  shopify:
    image: hieuhidro/shopify:themekit-1.3.1
    volumes:
      - ./:/shopify
      - ./config:/root/.config/shopify/config
      - ./.cache:/root/.cache
    environment:
      - THEMEKIT_PASSWORD=[Your theme password (https://apps.shopify.com/theme-access)]
      - THEMEKIT_THEME_ID=[Your theme ID]
      - THEMEKIT_STORE=[Your Store URL]
      - SHOPIFY_CLI_DEVICE_AUTH=[1|0]
      - "THEMEKIT_IGNORE_FILES=*.gif:*.jpg:config/settings_data.json"
    ports:
      - "3456:3456"
      - "9292:9292"
      - "8081:8081"
    # For nginx-proxy
    networks:
      - default
      - proxy

networks:
  proxy:
    external: true
