version: "3.8"
services:
  test-runner:
    image: test-runner:latest
    networks:
      - shared
    depends_on:
      - shopify

  shopify:
    image: shopify:latest
    volumes:
      - ./:/shopify
    environment:
      - SHOPIFY_CLI_THEME_TOKEN=shptka_ecb40f5d0a2702f1ce8d5d6b0d21fe77
      - SHOPIFY_FLAG_STORE=longruncoffee.myshopify.com
      - SHOPIFY_FLAG_HOST=0.0.0.0
      - SHOPIFY_CLI_TTY=0
    ports:
      - 9292:9292
    networks:
      - shared

networks:
  shared:
    external: true
