on:
  push:
    branches:
      - main
name: Notify Changes via Slack
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: AdamBot
          SLACK_CHANNEL: website
          SLACK_ICON_EMOJI: ":rocket:"
          SLACK_TITLE: "New Website Changes"
          SLACK_ICON: https://imgur.com/a/sgZzynC
